{difficulty
	(include "difficulty_generic.inc")
    {enemy
		{health 1.00}
		{armor 0.80}
		{burst 0.80}
		{accuracy 0.80}
		{firing_timeout 5.00}
		{grenade_timeout 3.50}
	}
	{ally
		{health 3.00}
		{armor 1.00}
		{burst 1.00}
		{accuracy 1.00}
		{firing_timeout 5.00}
		{grenade_timeout 3.50}
	}
	{player
		{health 3.00}
		{armor 1.00}
		{burst 1.00}
		{accuracy 1.00}
		{firing_timeout 5.00}
		{grenade_timeout 3.50}
	}
 	{neutral
		{health 3.00}
	}
}
